export default {
  SET_LOADER: 'SET_LOADER',
  SET_CARDS: 'SET_CARDS',
  ADD_MATCHED_CARD: 'ADD_MATCHED_CARD',
  UPDATE_CARD: 'UPDATE_CARD',
  SET_GAME_FINISHED: 'SET_GAME_FINISHED',
  SET_COUNT: 'SET_COUNT',
  SET_START_TIME: 'SET_START_TIME',
  SET_PLAY_TIME: 'SET_PLAY_TIME',
  SET_CURRENT_LEVEL: 'SET_CURRENT_LEVEL',
};
